# -*- coding: utf-8 -*-
"""Exercicios while

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFB69q-WuPUKgY34YfiExAmh1S5lcjv0

9-Escreva um programa que calcule a média de uma lista de números fornecida pelo usuário.
"""

numeros = int(input("Digite um numero: "))
contador = 0
soma = 0
while contador < 5:
  numeros = int(input("Digite mais um numero: "))
  contador += 1
  soma += numeros
  media = soma/contador
print(f"A media dos numeros é {media}")