# -*- coding: utf-8 -*-
"""Exercicios while

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFB69q-WuPUKgY34YfiExAmh1S5lcjv0

8-Escreva um programa que solicite ao usuário que insira uma senha. O programa deve continuar solicitando a senha até que o usuário insira a senha correta.
"""

senha_correta = "1234"
senha = input("Digite uma senha: ")
while senha != senha_correta:
 print("Senha incorreta")
 senha = input("Digite uma senha valida: ")
print("Senha correta")