# -*- coding: utf-8 -*-
"""Exercicios while

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFB69q-WuPUKgY34YfiExAmh1S5lcjv0

2-Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações.
"""

nome = input("Insira o nome de usuário: ")
senha = input("Insira a senha: ")
while senha == nome:
  print("Erro")
  nome = input("Insira o nome de usuário novamente: ")
  senha = input("Insira a senha novamente: ")
print("Usuário e senha corretos")