# -*- coding: utf-8 -*-
"""Exercicios while

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFB69q-WuPUKgY34YfiExAmh1S5lcjv0

10-Escreva um programa que solicite ao usuário que insira números até que ele insira o número 0. Em seguida, imprima a soma de todos os números inseridos.
"""

numero = float(input("Insira um numero: "))
soma = 0
while numero != 0:
  numero = float(input("Insira outro numero: "))
  soma += numero
print(f"A soma dos numeros que foram diferente de 0 é igual a {soma}")