# -*- coding: utf-8 -*-
"""Exercicios while

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFB69q-WuPUKgY34YfiExAmh1S5lcjv0

4-Escreva um programa que imprima os números pares de 1 a 20.
"""

numero = 2
while numero <= 20:
  print(numero)
  numero += 2