# -*- coding: utf-8 -*-
"""Exercicios while

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFB69q-WuPUKgY34YfiExAmh1S5lcjv0

3-Escreva um programa que conte de 1 a 10 e imprima cada número.
"""

numero = 1
while numero <= 10:
  print(numero)
  numero += 1