# -*- coding: utf-8 -*-
"""Exercicios while

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFB69q-WuPUKgY34YfiExAmh1S5lcjv0

5-Escreva um programa que solicite ao usuário que insira um número e, em seguida, imprima todos os números de 1 até esse número.
"""

numero = int(input("Digite um numero: "))
contador = 1
while contador <= numero:
  print(contador)
  contador += 1