# -*- coding: utf-8 -*-
"""Exercicios while

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFB69q-WuPUKgY34YfiExAmh1S5lcjv0

1- Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
"""

nota = float(input("Digite uma nota entre zero e dez: "))
while nota > 10 or nota < 0:
  nota = float(input("Digite um valor valido: "))
print("Sucesso")