# -*- coding: utf-8 -*-
"""Exercicios while

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFB69q-WuPUKgY34YfiExAmh1S5lcjv0

11-Escreva um programa que solicite ao usuário que insira números até que ele insira um número negativo. Em seguida, imprima o maior número inserido.
"""

maior_numero = 0
numero = float(input("Insira um número: "))
while numero >= 0:
    numero = float(input("Insira outro numero: "))
    if numero < 0:
     break
    elif numero > maior_numero:
      maior_numero = numero
print("O numero insirido é um numero negativo")
print(f"O maior número inserido é: {maior_numero}")