# -*- coding: utf-8 -*-
"""Exercicios while

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFB69q-WuPUKgY34YfiExAmh1S5lcjv0

7-Escreva um programa que solicite ao usuário que insira um número e, em seguida, imprima a tabuada desse número até 10.
"""

numero = int(input("Por favor,digite um numero: "))
contador = 1
while contador <= 10:
  resultado = numero * contador
  print(f"{numero} X {contador} = {resultado}")
  contador += 1